Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,7 +1,7 @@
 name: Main workflow
 on: push
 env: # Set the secret as an input
-  github_username: sorensenelena
+  github_username: ${{ github.actor }}
   github_password: ${{ secrets.GITHUB_TOKEN }} # Must be made available to the workflow
   GIT_COMMIT: ${{ github.sha }}
 jobs:
@@ -9,6 +9,16 @@ jobs:
     runs-on: ubuntu-latest
     container: gradle:6-jdk11
     steps:
+      - name: Validate GitHub username is all lowercase
+        id: validate_lower
+        run: |
+          if [[ "${{ env.github_username }}" =~ [A-Z] ]]; then
+            echo "::error::Validation Failed: GitHub username '${{ env.github_username }}' cannot contain uppercase characters."
+            exit 1
+          else
+            echo "GitHub username format is valid."
+          fi
+        shell: bash
       - name: Clone down repository
         uses: actions/checkout@v4       
       - name: Build application
@@ -23,7 +33,8 @@ jobs:
           include-hidden-files: true
   Linting:
     runs-on: ubuntu-latest
-    needs: [Build]
+    needs: 
+      - Build
     steps:
       - name: Download code
         uses: actions/download-artifact@v4
@@ -31,7 +42,7 @@ jobs:
           name: code
           path: .
       - name: run linting
-        uses: super-linter/super-linter/slim@v4
+        uses: super-linter/super-linter/slim@v7
         env:
           DEFAULT_BRANCH: main
           # To report GitHub Actions status checks
@@ -48,6 +59,8 @@ jobs:
         with:
           name: code
           path: .
+      - name: ls
+        run: ls -la ci
       - name: build docker
         run: bash ci/build-docker.sh
       - name: push docker
